const main=document.querySelector('main'), dialog=document.querySelector('#access-dialog'), dialogContent=document.querySelector('#dialog-content');
const territories=[
  ['Lead Self','Memimpin diri sebelum memimpin orang lain','Kesadaran diri, values, judgment, emotional regulation, resilience, learning, dan integritas dalam mengambil keputusan.'],
  ['Lead People','Membangun hubungan yang membuat orang dapat bertumbuh','Trust, psychological safety, feedback, coaching, delegation, collaboration, dan percakapan sulit.'],
  ['Lead Performance & Change','Menggerakkan hasil sekaligus membawa perubahan','Direction, accountability, decision-making, execution, performance, culture, adaptability, dan change leadership.']
];
const resources=[
  ['Lead Self','Article','Ketika Tekanan Membuatmu Bereaksi Terlalu Cepat','Mengenali trigger, menciptakan jeda, dan memilih respons yang lebih selaras dengan values serta situasi.'],
  ['Lead Self','Reflection tool','Pause - Notice - Choose','Reflection tool singkat untuk mengenali reaksi otomatis dan memilih respons yang lebih sadar.'],
  ['Lead People','Practical guide','Delegation Without Losing Control','Memetakan apa yang tetap dipegang, apa yang dilepas, dan apa yang harus tetap terlihat.'],
  ['Lead Performance & Change','Article','Akuntabilitas Tidak Selesai dengan Reminder','Lima area yang perlu diperiksa sebelum menyimpulkan bahwa tim tidak memiliki ownership.'],
  ['Lead Performance & Change','Diagnostic','Accountability Reality Check','Melihat area mana yang paling membutuhkan perhatian dalam sebuah komitmen.']
];
const events=[
  ['UNPACKED #01','Why Good Managers Still Struggle to Lead','Membongkar pola, sistem, dan asumsi yang membuat manager baik tetap kesulitan membangun ownership dan kualitas keputusan.','Member Only','Online · Tanggal akan diumumkan'],
  ['ON THE TABLE #01','What Should I Still Hold, Delegate, or Redesign?','Bawa satu situasi nyata dan olah bersama curated peers untuk pulang dengan satu langkah yang lebih jelas.','Invite Only','September W3 · Offline / Online'],
  ['BETWEEN THE LINES #01','What the Team Is Not Saying','Membaca sinyal, silence, dan dinamika di balik percakapan tim.','Member Only','Online · Tanggal akan diumumkan'],
  ['MAKE IT WORK #01','Delegation Without Losing Control','Practical lab untuk menyusun Delegation Agreement yang jelas dan dapat digunakan.','Member Only','Offline · Tanggal akan diumumkan'],
  ['BERDAYA ASSEMBLY #01','Leadership That People Can Feel','Pertemuan lintas perspektif tentang cara leader memimpin diri, relasi, dan perubahan.','Member Only','Offline · Tanggal akan diumumkan']
];
const button=(text,route,cls='button')=>`<a class="${cls}" href="#${route}">${text} <span aria-hidden="true">→</span></a>`;
function home(){return `<section class="hero"><div class="shell"><div class="hero-copy"><div class="kicker">Curated behavioral leadership community</div><h1>Leadership challenges do not have to be <em>figured out alone.</em></h1><p class="lede">BERDAYA membantu HR/HC Professionals, People Leaders, dan Business Owners menghadapi situasi kepemimpinan nyata melalui trusted knowledge, practical tools, dan curated conversations.</p>${button('Jelajahi BERDAYA','about')} ${button('Mulai dari situasimu','learn','button ghost')}</div></div><div class="shell hero-side" aria-hidden="true"><div class="orbit"></div><article class="note-card"><span class="kicker">Learn</span><strong>From what is real.</strong><p>Knowledge yang membantu membaca situasi sebelum memilih langkah.</p></article><article class="note-card"><span class="kicker">Contribute</span><strong>Bring the question to the table.</strong><p>Ruang tumbuh melalui pengalaman, refleksi, dan pertukaran yang tepercaya.</p></article></div></section><section class="section"><div class="shell"><div class="section-head"><div><div class="kicker">Tentang BERDAYA</div><h2>Knowledge, tools, dan pengalaman yang dekat dengan situasi nyata.</h2></div><p>Dayalima menghadirkan knowledge, tools, dan experiences; member menghidupkan ruang melalui pengalaman, pertanyaan, refleksi, serta kontribusi yang relevan.</p></div><div class="value-grid"><article class="value"><span class="number">01</span><b>Situasi nyata, bukan teori berdiri sendiri.</b><p>Mulai dari tantangan leadership yang benar-benar sedang dihadapi.</p></article><article class="value"><span class="number">02</span><b>Knowledge yang dapat dipraktikkan.</b><p>Insight dikurasi dan diterjemahkan menjadi tools serta langkah praktis.</p></article><article class="value"><span class="number">03</span><b>Community yang berpartisipasi.</b><p>Ruang belajar dibangun lewat contribution, bukan silent membership.</p></article></div></div></section><section class="section alt"><div class="shell"><p class="statement">A practical learning community for <em>real leadership situations.</em></p></div></section><section class="section"><div class="shell"><div class="section-head"><div><div class="kicker">Explore leadership situations</div><h2>Mulai dari situasi yang sedang kamu hadapi.</h2></div><p>Jelajahi tiga wilayah leadership behavior, lalu temukan resource dan conversation yang relevan.</p></div>${territoryCards()}</div></section>`}
function territoryCards(){return `<div class="territory-grid">${territories.map((t,i)=>`<article class="territory"><span class="number">0${i+1}</span><h2>${t[0]}</h2><strong>${t[1]}</strong><p>${t[2]}</p><a href="#learn">Jelajahi resource →</a></article>`).join('')}</div>`}
function about(){return pageHero('Apa itu BERDAYA','Curated behavioral leadership community, powered by Dayalima.','BERDAYA mempertemukan curated knowledge dari Dayalima dengan pengalaman nyata para member. Fokusnya membantu member memahami situasi, menguji cara berpikir, mencoba tools, dan membawa pembelajaran kembali ke pekerjaan sehari-hari.')+`<section class="content-wrap"><div class="shell"><div class="section-head"><div><div class="kicker">BERDAYA untuk siapa</div><h2>Untuk mereka yang membentuk cara organisasi bekerja.</h2></div></div><div class="value-grid"><article class="value"><span class="number">01</span><b>HR/HC Professionals</b><p>Mendesain, mengembangkan, dan menguatkan perilaku leadership dalam organisasi.</p></article><article class="value"><span class="number">02</span><b>People Leaders</b><p>Menerapkan leadership melalui komunikasi, keputusan, feedback, delegation, dan performance sehari-hari.</p></article><article class="value"><span class="number">03</span><b>Business Owners</b><p>Menentukan teladan, arah culture, authority, dan consequence yang membentuk perilaku organisasi.</p></article></div><div class="policy"><strong>Yang membedakan BERDAYA</strong><br/>Berangkat dari leadership situation yang nyata; knowledge dikurasi menjadi langkah praktis; dan community dibangun melalui partisipasi.</div></div></section>`}
function learn(){let groups=territories.map(t=>`<section class="resource-group"><div class="kicker">${t[0]}</div><h2>${t[1]}</h2><div class="resource-list">${resources.filter(r=>r[0]===t[0]).map(resource).join('')}</div></section>`).join('');return pageHero('Learn','Temukan resource yang membantu membaca situasi sebelum memilih respons.','Preview tersedia untuk semua pengunjung. Artikel lengkap, diagnostic, dan practical guide tersedia untuk member setelah login.')+`<section class="content-wrap"><div class="shell">${territoryCards()}${groups}</div></section>`}
function resource(r){return `<article class="resource"><small>${r[1].toUpperCase()}</small><div><h3>${r[2]}</h3><p>${r[3]}</p></div><button class="tag gated" data-title="${r[2]}">MEMBER ONLY</button></article>`}
function eventsPage(){return pageHero('Events','Ruang untuk membawa leadership situation ke dalam percakapan yang tepat.','Pilih pengalaman yang sesuai dengan situasi, format, dan kebutuhanmu.')+`<section class="content-wrap"><div class="shell"><div class="filters"><button class="filter active">Semua</button><button class="filter">Member Only</button><button class="filter">Open / Invite Only</button><button class="filter">Online</button><button class="filter">Offline</button></div><div class="event-grid">${events.map(eventCard).join('')}</div><section class="section alt"><div class="shell"><div class="kicker">Member rhythm</div><h2>Monday Pulse & Friday Check-out</h2><p>Reflection prompt singkat di WhatsApp Group member untuk menjaga fokus, membagikan pembelajaran, dan menentukan next move.</p></div></section></div></section>`}
function eventCard(e){return `<article class="event-card"><span class="kicker">${e[0]}</span><h2>${e[1]}</h2><p>${e[2]}</p><div class="event-meta">${e[4]}<br/><strong>Akses: ${e[3]}</strong></div><button class="button gated" data-title="${e[1]}">${e[3]==='Invite Only'?'Lihat detail':'Cek akses'} →</button></article>`}
function membership(){return pageHero('Membership','A curated community for leaders who learn, contribute, and grow together.','Membership memberi akses pada knowledge, tools, reflection, serta curated experiences. Nilainya tumbuh ketika setiap member hadir sebagai learner sekaligus contributor.')+`<section class="content-wrap"><div class="shell membership-layout"><div><div class="kicker">Membership ini cocok untukmu jika</div><h2>Kamu datang dengan situasi nyata dan bersedia belajar bersama.</h2><p>Kamu memegang peran terkait people dan leadership, ingin memahami atau mengerjakan situasi nyata, dan siap berkontribusi dalam ruang bersama.</p><div class="benefit-grid"><article class="benefit"><b>Curated knowledge</b><p>Artikel, diagnostic tools, dan practical guides lengkap.</p></article><article class="benefit"><b>Relevant experiences</b><p>Invitation atau prioritas ke signature experiences tertentu.</p></article><article class="benefit"><b>Trusted exchange</b><p>Ruang belajar bersama peers dengan tanggung jawab relevan.</p></article></div><div class="policy"><strong>Membership tumbuh melalui partisipasi.</strong><br/>Member diharapkan menjaga confidentiality, menghormati perbedaan, tidak melakukan unsolicited selling, dan merespons check-in komunitas.</div></div>${applicationForm()}</div></section>`}
function applicationForm(){return `<form class="form-panel application-form"><h2>Apply for Membership</h2><p>Pengisian form belum otomatis menjadikan kamu member.</p><div class="form-grid"><div class="field"><label>Nama lengkap *</label><input required name="name" autocomplete="name"/></div><div class="field"><label>Jabatan *</label><input required name="role"/></div><div class="field full"><label>Perusahaan atau organisasi *</label><input required name="org"/></div><div class="field"><label>Email aktif *</label><input required type="email" name="email" autocomplete="email"/></div><div class="field"><label>Nomor WhatsApp *</label><input required name="phone" autocomplete="tel"/></div><div class="field"><label>Kota domisili</label><input name="city"/></div><div class="field"><label>Peran utama *</label><select required><option value="">Pilih peran</option><option>HR/HC Professional</option><option>People Leader</option><option>Business Owner</option></select></div><div class="field full"><label>Leadership challenge apa yang sedang kamu hadapi? *</label><textarea required></textarea></div><div class="field full"><label>Kontribusi atau perspektif apa yang ingin kamu bawa? *</label><textarea required></textarea></div></div><label class="consent"><input required type="checkbox"/> Saya bersedia berpartisipasi aktif dan mengikuti community guidelines. *</label><label class="consent"><input required type="checkbox"/> Saya menyetujui pengelolaan data sesuai Privacy Policy. *</label><label class="consent"><input type="checkbox"/> Saya bersedia menerima komunikasi komersial dari Dayalima. (Opsional)</label><button class="button" type="submit">Submit Application →</button></form>`}
function faq(){const q=[['Apakah BERDAYA hanya untuk HR?','Tidak. BERDAYA dirancang untuk HR/HC Professionals, People Leaders, dan Business Owners.'],['Apakah saya harus menjadi member untuk mengakses konten?','Non-member dapat melihat preview resource dan detail event. Artikel lengkap, tools, guides, Member Rhythm, dan event khusus tersedia setelah member login.'],['Apakah konten dan kegiatan BERDAYA berbayar?','Saat ini, konten dan kegiatan dapat diakses tanpa biaya oleh member. Jika ada program khusus berbayar, informasi biaya akan disampaikan sebelum pendaftaran.'],['Bagaimana proses seleksi member?','Tim meninjau relevansi peran, leadership challenge, niat berkontribusi, community fit, dan ketersediaan ruang.'],['Apa yang dimaksud berkontribusi aktif?','Member dapat bertanya, memberi feedback, membawa kasus, mengikuti reflection prompt, hadir di event, atau membagikan pembelajaran yang relevan.'],['Apakah cerita yang dibagikan aman?','Member wajib menjaga confidentiality. Aturan dokumentasi, data, dan batas kerahasiaan akan dijelaskan sebelum aktivitas dimulai.']];return pageHero('FAQ','Jawaban singkat untuk memulai perjalananmu di BERDAYA.','Jika pertanyaanmu belum terjawab, hubungi tim BERDAYA melalui kanal resmi Dayalima.')+`<section class="content-wrap"><div class="shell"><div class="faq-list">${q.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></div></section>`}
function login(){return pageHero('Member Login','Masuk untuk melanjutkan dari situasi, resource, atau event yang paling relevan.','Akun akan diaktifkan setelah aplikasi membership disetujui oleh tim BERDAYA.')+`<section class="content-wrap"><div class="shell login-layout"><aside class="member-preview"><div class="kicker">Member Home</div><h2>Semua yang kamu butuhkan untuk terus bergerak.</h2><p>Recommended resource, My Tools, My Events, Member Rhythm, dan Profile & Preferences.</p></aside><form class="form-panel login-form"><h2>Login</h2><div class="field"><label>Email</label><input type="email" required autocomplete="email"/></div><div class="field"><label>Password</label><input type="password" required autocomplete="current-password"/></div><button class="button" type="submit">Masuk →</button><p><a href="#membership">Belum menjadi member? Apply for Membership</a></p></form></div></section>`}
function dashboard(){return pageHero('Member Home','Selamat datang kembali, Member.','Lanjutkan dari situasi, resource, atau event yang paling relevan untukmu.')+`<section class="content-wrap"><div class="shell dashboard"><aside class="dashboard-nav"><a href="#learn">Recommended for you</a><a href="#learn">My Tools</a><a href="#events">My Events</a><a href="#events">Member Rhythm</a><a href="#membership">Profile & Preferences</a></aside><div><article class="dash-card"><div class="kicker">Recommended for you</div><h3>Delegation Without Losing Control</h3><p>Practical guide untuk memetakan decision rights, guardrails, checkpoint, dan escalation.</p>${button('Buka guide','learn')}</article><article class="dash-card"><div class="kicker">Member Rhythm</div><h3>Monday Pulse</h3><p>Situasi atau keputusan apa yang perlu kamu beri perhatian minggu ini?</p></article></div></div></section>`}
function pageHero(kicker,title,text){return `<section class="page-hero"><div class="shell"><div class="kicker">${kicker}</div><h1>${title}</h1><p>${text}</p></div></section>`}
function render(){let route=location.hash.slice(1)||'home';let pages={home,about,learn,events:eventsPage,membership,faq,login,dashboard};main.innerHTML=(pages[route]||home)();document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${route}`));document.querySelector('.main-nav').classList.remove('open');bind();window.scrollTo(0,0)}
function bind(){document.querySelectorAll('.gated').forEach(x=>x.onclick=()=>{dialogContent.innerHTML=`<div class="kicker">Member access</div><h2>${x.dataset.title}</h2><p>Preview resource tersedia untuk semua. Untuk membuka konten lengkap, menggunakan tool, atau mendaftar event khusus member, ajukan membership terlebih dahulu.</p>${button('Apply for Membership','membership')}`;dialog.showModal()});document.querySelector('.application-form')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.innerHTML=`<div class="kicker">Application received</div><h2>Terima kasih. Aplikasimu sudah kami terima.</h2><p>Tim BERDAYA akan meninjau kecocokan peran, challenge, niat berkontribusi, dan ketersediaan ruang. Langkah berikutnya akan dikirim melalui email atau WhatsApp.</p>`});document.querySelector('.login-form')?.addEventListener('submit',e=>{e.preventDefault();location.hash='dashboard'})}
document.querySelector('.menu-toggle').onclick=()=>{let n=document.querySelector('.main-nav'),b=document.querySelector('.menu-toggle');n.classList.toggle('open');b.setAttribute('aria-expanded',n.classList.contains('open'))};document.querySelector('.dialog-close').onclick=()=>dialog.close();window.addEventListener('hashchange',render);render();document.querySelector('#site-footer').innerHTML=`<div class="shell footer-grid"><div><div class="brand"><span class="brand-mark">B</span><span>BERDAYA<small>by Dayalima</small></span></div><p>Curated behavioral leadership community powered by Dayalima.</p></div><div><h3>Explore</h3><a href="#about">About BERDAYA</a><a href="#learn">Learn</a><a href="#events">Events</a><a href="#membership">Membership</a></div><div><h3>Help</h3><a href="#faq">FAQ</a><a href="#membership">Contact BERDAYA</a><a href="#faq">Privacy Policy</a><a href="#faq">Community Guidelines</a></div><div><h3>Member</h3><a href="#login">Login</a><a href="#membership">Sign Up</a><a href="#dashboard">Member Home</a></div></div><div class="shell footer-bottom">BERDAYA by Dayalima · Temporary home: dayalima.space</div>`;
